### ISSUE TITLE
Neo4j process isn't terminated correctly

### ISSUE THREAD

**Issue by bsphere** [tpires/neo4j#5]
resulting in 10secs delay, and db recover on next startup.

this is because the image is launching a .sh script, which doesn't pass the termination signal to the sub processes, as described in https://github.com/docker/docker/issues/2436

**Comment by tpires** [comment]
If you execute the container without -it flags does it have the same behavior ?

**Comment by bsphere** [comment]
yes, it is the behavior of Docker... it sends signals only to the process
it launched and not to forked processes..

**Comment by tpires** [comment]
Does this still happen?
