### ISSUE TITLE
Add support for setting auth credentials via environment variables

### ISSUE THREAD

**Issue by pandeiro** [tpires/neo4j#9]
This is a common pattern (see: [official postgres image](https://registry.hub.docker.com/_/postgres/)), which uses environment variables, e.g. `NEO4J_USER` and `NEO4J_PASSWORD`, to create these credentials in the container.

Would this be possible?

**Comment by pandeiro** [comment]
Just to clarify the use case, it seems that it is no longer possible to connect to new neo4j container without authenticating -- is this new/recent behavior? (Previously I could connect without specifying this.)

**Comment by pandeiro** [comment]
Re: my comment above, the recent [2.2.0 release](http://neo4j.com/release-notes/neo4j-2-2-0/) of Neo4J is what made authentication mandatory.

It may be preferable to peg your image to a specific version (ie, not "stable") so that automatic rebuilds on the Docker Registry don't result in silent version bumps.

**Comment by noazark** [comment]
I'm with @pandeiro on this one. It would be nice to have some env vars for authentication.

**Comment by DavidBadura** [comment]
it exists a fork with this feature https://github.com/artsince/docker-neo4j 
@artsince can you please create a pull request :wink: 
it would be very nice :-)

**Comment by artsince** [comment]
@DavidBadura I created the PR #10

**Comment by artsince** [comment]
and the docker repository for the fork is here: https://registry.hub.docker.com/u/ahmetkizilay/docker-neo4j/

**Comment by DavidBadura** [comment]
Thank you :-)

**Comment by DavidBadura** [comment]
this can be closed :) ref #10
